name: Pull Request

on:
    pull_request

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ["ubi8", "ubi10", "trixie"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - run: |
             if [[ "${{ matrix.name }}" == "trixie" ]]; then
             cat spideroak-deb-2016.asc | gpg --dearmor | tee spideroak.gpg > /dev/null
             fi
      - name: Build the Docker image
        run: docker build . --file Dockerfile.${{ matrix.name }} -t ${{ vars.DOCKERHUB_USERNAME }}/spideroak-${{ matrix.name }}:latest
      - name: Test the image
        run: docker run --rm --entrypoint=/usr/bin/SpiderOakONE ${{ vars.DOCKERHUB_USERNAME }}/spideroak-${{ matrix.name }}:latest --version
